### ISSUE TITLE
Starting crash

### ISSUE THREAD

**Issue by kotleni** [faceslog/SteamPlaytimeBooster#1]
```root@v1975777:~/SteamPlaytimeBooster# npm run serve

> steamplaytimebooster@1.0.0 serve
> node index.js

/root/SteamPlaytimeBooster/src/clientController.js:39
    #login()
          ^

SyntaxError: Unexpected token '('
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/root/SteamPlaytimeBooster/index.js:2:16)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)```

**Comment by faceslog** [comment]
Hello what is your node js version ? node -v

This seems to be due to the use of a private class method, indicated by the # symbol before the method name, which is a feature of modern js (ES2022). This feature might not be supported in your current Node.js version.

**Comment by kotleni** [comment]
> Hello what is your node js version ? node -v
> 
> This seems to be due to the use of a private class method, indicated by the # symbol before the method name, which is a feature of modern js (ES2022). This feature might not be supported in your current Node.js version.

It's v12.22.9

**Comment by faceslog** [comment]
> > Hello what is your node js version ? node -v
> > 
> > This seems to be due to the use of a private class method, indicated by the # symbol before the method name, which is a feature of modern js (ES2022). This feature might not be supported in your current Node.js version.
> 
> It's v12.22.9

As stated in the READ ME you need a newer version of nodejs. At least NodeJS LTS (16+)

Regards
